version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mariadb:10.5
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=django_db
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=django_password
      - MYSQL_ROOT_PASSWORD=root_password

volumes:
  mariadb_data:
